export const SAVE_FORM_INFO_FETCH = 'SAVE_FORM_INFO_FETCH';
export const SAVE_FORM_INFO_SUCCESS = 'SAVE_FORM_INFO_SUCCESS';
export const SAVE_FORM_INFO_ERROR = 'SAVE_FORM_INFO_ERROR';

export const GET_FORM_INFO_FETCH = 'GET_FORM_INFO_FETCH';
export const GET_FORM_INFO_SUCCESS = 'GET_FORM_INFO_SUCCESS';
export const GET_FORM_INFO_ERROR = 'GET_FORM_INFO_ERROR';
